export interface GitmojiItem { emoji:string; code:string; description:string; keywords:string[] }

// Curated from the open-source Gitmoji guide. Unicode emoji rendering is provided by the user's platform.
export const GITMOJIS: GitmojiItem[] = [
  {emoji:'🎨',code:':art:',description:'Mejorar estructura o formato',keywords:['design','format','style']},
  {emoji:'⚡️',code:':zap:',description:'Mejorar rendimiento',keywords:['performance','speed']},
  {emoji:'🔥',code:':fire:',description:'Eliminar código o archivos',keywords:['remove','delete']},
  {emoji:'🐛',code:':bug:',description:'Corregir un bug',keywords:['bug','fix']},
  {emoji:'🚑️',code:':ambulance:',description:'Hotfix crítico',keywords:['hotfix','critical']},
  {emoji:'✨',code:':sparkles:',description:'Nueva funcionalidad',keywords:['feature','new']},
  {emoji:'📝',code:':memo:',description:'Documentación',keywords:['docs','notes']},
  {emoji:'🚀',code:':rocket:',description:'Deploy / lanzamiento',keywords:['deploy','launch']},
  {emoji:'💄',code:':lipstick:',description:'UI y estilos',keywords:['ui','css','style']},
  {emoji:'🎉',code:':tada:',description:'Inicio de proyecto',keywords:['start','project']},
  {emoji:'✅',code:':white_check_mark:',description:'Tests correctos',keywords:['test','check']},
  {emoji:'🔒️',code:':lock:',description:'Seguridad o privacidad',keywords:['security','privacy']},
  {emoji:'🔖',code:':bookmark:',description:'Release / versión',keywords:['release','version']},
  {emoji:'🚨',code:':rotating_light:',description:'Warnings de linter/compilador',keywords:['lint','warning']},
  {emoji:'🚧',code:':construction:',description:'Trabajo en progreso',keywords:['wip','construction']},
  {emoji:'🚚',code:':truck:',description:'Mover o renombrar recursos',keywords:['move','rename']},
  {emoji:'💥',code:':boom:',description:'Breaking change',keywords:['breaking']},
  {emoji:'🍱',code:':bento:',description:'Assets',keywords:['asset','image']},
  {emoji:'♿️',code:':wheelchair:',description:'Accesibilidad',keywords:['a11y','accessibility']},
  {emoji:'💡',code:':bulb:',description:'Comentarios o explicación',keywords:['idea','comment']},
  {emoji:'💬',code:':speech_balloon:',description:'Texto y literales',keywords:['text','copy']},
  {emoji:'🗃️',code:':card_file_box:',description:'Base de datos',keywords:['database','db']},
  {emoji:'🔊',code:':loud_sound:',description:'Logs',keywords:['log']},
  {emoji:'👥',code:':busts_in_silhouette:',description:'Personas / equipo',keywords:['people','team']},
  {emoji:'🚸',code:':children_crossing:',description:'UX / usabilidad',keywords:['ux','usability']},
  {emoji:'🏗️',code:':building_construction:',description:'Arquitectura',keywords:['architecture']},
  {emoji:'📱',code:':iphone:',description:'Responsive / mobile',keywords:['mobile','responsive']},
  {emoji:'🤡',code:':clown_face:',description:'Mocks',keywords:['mock']},
  {emoji:'📸',code:':camera_flash:',description:'Snapshots / captura',keywords:['snapshot','image']},
  {emoji:'⚗️',code:':alembic:',description:'Experimento',keywords:['experiment']},
  {emoji:'🔍️',code:':mag:',description:'Búsqueda / inspección',keywords:['search','inspect']},
  {emoji:'🏷️',code:':label:',description:'Tipos / etiquetas',keywords:['type','label']},
  {emoji:'🌱',code:':seedling:',description:'Datos iniciales / crecimiento',keywords:['seed','growth']},
  {emoji:'🚩',code:':triangular_flag_on_post:',description:'Feature flag',keywords:['flag','feature']},
  {emoji:'🥅',code:':goal_net:',description:'Manejo de errores',keywords:['error','catch']},
  {emoji:'💫',code:':dizzy:',description:'Animaciones y transiciones',keywords:['animation','transition']},
  {emoji:'🧐',code:':monocle_face:',description:'Exploración / inspección',keywords:['inspect','data']},
  {emoji:'🧪',code:':test_tube:',description:'Prueba / experimento',keywords:['test','experiment']},
  {emoji:'👔',code:':necktie:',description:'Lógica de negocio',keywords:['business']},
  {emoji:'🧱',code:':bricks:',description:'Infraestructura',keywords:['infra','infrastructure']},
  {emoji:'🧑‍💻',code:':technologist:',description:'Developer experience',keywords:['developer','dx']},
  {emoji:'✈️',code:':airplane:',description:'Soporte offline',keywords:['offline']},
];
