import type { ArchitectureNode, SlideBlock } from '../types';
import { RichTextInput } from './RichTextInput';
import { MarkdownBlockView } from '../components/MarkdownBlock';
import { defaultBlock } from './templates';

const lines = (value: string) => value.split('\n').map((item) => item.trim()).filter(Boolean);
const join = (items: string[]) => items.join('\n');

/**
 * Textarea de lista. No normaliza mientras se escribe: si filtráramos las líneas
 * vacías en cada tecla, al apretar Enter la línea nueva desaparecería al instante y
 * sería imposible agregar ítems. Recién al salir del campo se limpian vacías y espacios.
 */
function ListTextarea({ label, items, onChange }: { label: string; items: string[]; onChange: (items: string[]) => void }) {
  return <label>{label}<textarea value={join(items)}
    onChange={(e) => onChange(e.target.value.split('\n'))}
    onBlur={(e) => onChange(lines(e.target.value))} /></label>;
}

/** Cabecera de un ítem repetible: número + borrar. */
function ItemHead({ title, onRemove, disabled }: { title: string; onRemove: () => void; disabled?: boolean }) {
  return <div className="sub-editor-head"><strong>{title}</strong><button className="sub-editor-remove" title="Eliminar" disabled={disabled} onClick={onRemove}>×</button></div>;
}
function AddItem({ label, onClick }: { label: string; onClick: () => void }) {
  return <button className="secondary-button full-width" onClick={onClick}>+ {label}</button>;
}

const nestedBlockLabels: Record<SlideBlock['type'], string> = { text:'Texto',markdown:'Markdown',bullets:'Bullets',cards:'Cards',stats:'KPIs',callout:'Callout',quote:'Quote',code:'Código',terminal:'Terminal',image:'Imagen',chart:'Chart',simulation:'Simulación',architecture:'Arquitectura',compare:'Comparación',timeline:'Timeline',tabs:'Tabs',steps:'Pasos',quadrant:'Matriz',columns:'Columnas',tooltip:'Tooltip',modal:'Modal',accordion:'Acordeón',drawer:'Panel lateral',flipcard:'Flip card',beforeAfter:'Antes / Después',hotspots:'Hotspots' };
const nestedBlockTypes = Object.keys(nestedBlockLabels) as SlideBlock['type'][];

/** Editor recursivo para cualquier bloque dentro de un contenedor. */
function NestedBlocksEditor({ label, blocks, onChange }: { label: string; blocks: SlideBlock[]; onChange: (blocks: SlideBlock[]) => void }) {
  const move = (index: number, offset: number) => {
    const next = [...blocks];
    [next[index], next[index + offset]] = [next[index + offset], next[index]];
    onChange(next);
  };
  return <div className="nested-blocks-editor">
    <div className="nested-blocks-title"><strong>{label}</strong><small>{blocks.length} bloque{blocks.length === 1 ? '' : 's'}</small></div>
    {blocks.map((inner, index) => <div className="sub-editor nested-block-editor" key={index}>
      <ItemHead title={nestedBlockLabels[inner.type]} onRemove={() => onChange(blocks.filter((_, i) => i !== index))} />
      <div className="nested-block-order"><button type="button" disabled={index === 0} aria-label="Subir bloque" onClick={() => move(index, -1)}>↑ Subir</button><button type="button" disabled={index === blocks.length - 1} aria-label="Bajar bloque" onClick={() => move(index, 1)}>↓ Bajar</button></div>
      <label>Tipo<select value={inner.type} onChange={event => onChange(blocks.map((item, i) => i === index ? defaultBlock(event.target.value as SlideBlock['type']) : item))}>{nestedBlockTypes.map(type => <option value={type} key={type}>{nestedBlockLabels[type]}</option>)}</select></label>
      <BlockEditor embedded block={inner} onChange={next => onChange(blocks.map((item, i) => i === index ? next : item))} />
    </div>)}
    <AddItem label="Bloque interno" onClick={() => onChange([...blocks, defaultBlock('text')])} />
  </div>;
}
/** `embedded` se usa cuando el bloque vive dentro de un elemento de canvas: ahí la
 *  animación y el borrado los maneja el inspector del elemento, no el bloque. */
type Props = { block: SlideBlock; onChange: (block: SlideBlock) => void; onDelete?: () => void; embedded?: boolean };

export function BlockEditor({ block, onChange, onDelete, embedded = false }: Props) {
  const meta = <><div className="block-meta-row"><label>Animación<select value={block.animation ?? 'none'} onChange={(e)=>onChange({...block, animation:e.target.value as SlideBlock['animation']})}><option value="none">None</option><option value="fade">Fade</option><option value="slide-up">Slide up</option><option value="slide-left">Slide left</option><option value="slide-right">Slide right</option><option value="zoom">Zoom</option><option value="bounce">Bounce</option><option value="blur">Blur</option><option value="rotate">Rotate</option><option value="motion-path">Motion path</option></select></label><label>Fragment<input type="number" min="0" max="20" value={block.fragment ?? 0} onChange={(e)=>onChange({...block,fragment:Number(e.target.value)})}/></label></div><div className="block-meta-row"><label>Duración (s)<input type="number" min="0.1" max="5" step="0.05" value={block.animationDuration??0.38} onChange={e=>onChange({...block,animationDuration:Number(e.target.value)})}/></label><label>Delay (s)<input type="number" min="0" max="5" step="0.05" value={block.animationDelay??0} onChange={e=>onChange({...block,animationDelay:Number(e.target.value)})}/></label></div><label>Easing<select value={block.animationEasing??'ease'} onChange={e=>onChange({...block,animationEasing:e.target.value as SlideBlock['animationEasing']})}><option value="ease">Ease</option><option value="ease-in">Ease in</option><option value="ease-out">Ease out</option><option value="ease-in-out">Ease in/out</option><option value="spring">Spring</option></select></label></>;
  return <div className={`block-editor ${embedded ? 'embedded' : ''}`}>
    {!embedded && <div className="block-editor-head"><strong>{block.type}</strong><button onClick={onDelete}>Eliminar</button></div>}
    {block.type === 'text' && <><RichTextInput label="Texto" value={block.text} onChange={(text)=>onChange({...block,text})}/><label className="check-row"><input type="checkbox" checked={Boolean(block.lead)} onChange={(e) => onChange({ ...block, lead: e.target.checked })} /> Texto destacado</label></>}
    {block.type === 'markdown' && <><label>Estilo<select value={block.appearance ?? 'modern'} onChange={(e)=>onChange({...block,appearance:e.target.value as Extract<SlideBlock,{type:'markdown'}>['appearance']})}><option value="modern">Modern</option><option value="paper">Paper</option><option value="minimal">Minimal</option><option value="card">Card</option><option value="notebook">Notebook</option><option value="contrast">Contrast</option><option value="terminal">Terminal</option></select></label><label>Markdown<textarea className="mono-input markdown-input" spellCheck={false} value={block.markdown} onChange={(e)=>onChange({...block,markdown:e.target.value})}/></label><details className="markdown-help"><summary>Ayuda rápida Markdown</summary><code># Título · **negrita** · *cursiva* · `código` · [link](https://...) · listas · tablas · ```lenguaje</code></details><div className="markdown-editor-preview"><small>PREVIEW</small><MarkdownBlockView markdown={block.markdown} appearance={block.appearance}/></div></>}
    {block.type === 'bullets' && <ListTextarea label="Un punto por línea" items={block.items} onChange={(items) => onChange({ ...block, items })} />}
    {block.type === 'cards' && <><label>Columnas<select value={block.columns ?? 3} onChange={(e) => onChange({ ...block, columns: Number(e.target.value) as 2 | 3 | 4 })}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>{block.items.map((item, i) => <div className="sub-editor" key={i}><ItemHead title={`Card ${i + 1}`} disabled={block.items.length <= 1} onRemove={() => onChange({ ...block, items: block.items.filter((_, n) => n !== i) })} /><label>Título<input value={item.title} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, title: e.target.value } : x) })} /></label><label>Texto<textarea value={item.text} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, text: e.target.value } : x) })} /></label></div>)}<AddItem label="Card" onClick={() => onChange({ ...block, items: [...block.items, { title: `Card ${block.items.length + 1}`, text: 'Descripción' }] })} /></>}
    {block.type === 'stats' && <>{block.items.map((item, i) => <div className="sub-editor" key={i}><ItemHead title={`KPI ${i + 1}`} disabled={block.items.length <= 1} onRemove={() => onChange({ ...block, items: block.items.filter((_, n) => n !== i) })} /><label>Valor<input value={item.value} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, value: e.target.value } : x) })} /></label><label>Etiqueta<input value={item.label} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, label: e.target.value } : x) })} /></label></div>)}<AddItem label="KPI" onClick={() => onChange({ ...block, items: [...block.items, { value: '0%', label: 'Métrica' }] })} /></>}
    {block.type === 'compare' && <div className="compare-editor">{(['left', 'right'] as const).map((side) => <div className="sub-editor" key={side}><strong>{side === 'left' ? 'Izquierda' : 'Derecha'}</strong><label>Etiqueta<input value={block[side].label} onChange={(e) => onChange({ ...block, [side]: { ...block[side], label: e.target.value } })} /></label><label>Título<input value={block[side].title} onChange={(e) => onChange({ ...block, [side]: { ...block[side], title: e.target.value } })} /></label><ListTextarea label="Items" items={block[side].items} onChange={(items) => onChange({ ...block, [side]: { ...block[side], items } })} /></div>)}</div>}
    {block.type === 'code' && <><label>Título<input value={block.title ?? ''} onChange={(e)=>onChange({...block,title:e.target.value})}/></label><label>Lenguaje<input value={block.language ?? ''} onChange={(e) => onChange({ ...block, language: e.target.value })} /></label><div className="field-row"><label>Marco<select value={block.frameStyle??'classic'} onChange={e=>onChange({...block,frameStyle:e.target.value as Extract<SlideBlock,{type:'code'}>['frameStyle']})}><option value="classic">Classic</option><option value="carbon">Carbon Gradient</option><option value="carbon-glass">Carbon Glass</option><option value="carbon-light">Carbon Light</option><option value="minimal">Minimal</option><option value="neon">Neon</option><option value="terminal">Terminal</option><option value="paper">Paper</option><option value="notebook">Notebook</option></select></label><label>Tema<select value={block.codeTheme??'seti'} onChange={e=>onChange({...block,codeTheme:e.target.value as Extract<SlideBlock,{type:'code'}>['codeTheme']})}><option value="seti">Seti</option><option value="night-owl">Night Owl</option><option value="dracula">Dracula</option><option value="nord">Nord</option><option value="github-dark">GitHub Dark</option><option value="monokai">Monokai</option><option value="one-dark">One Dark</option><option value="tokyo-night">Tokyo Night</option><option value="catppuccin">Catppuccin</option><option value="gruvbox">Gruvbox</option><option value="solarized-dark">Solarized Dark</option><option value="synthwave">Synthwave</option><option value="github-light">GitHub Light</option><option value="solarized-light">Solarized Light</option><option value="ayu-light">Ayu Light</option></select></label></div><div className="field-row"><label className="check-row"><input type="checkbox" checked={Boolean(block.showLineNumbers)} onChange={e=>onChange({...block,showLineNumbers:e.target.checked})}/> Números de línea</label><label className="check-row"><input type="checkbox" checked={block.showWindowControls!==false} onChange={e=>onChange({...block,showWindowControls:e.target.checked})}/> Controles ventana</label></div><label>Código<textarea className="mono-input" value={block.code} onChange={(e) => onChange({ ...block, code: e.target.value })} /></label></>}
    {block.type === 'terminal' && <><label>Comando<input value={block.command} onChange={(e) => onChange({ ...block, command: e.target.value })} /></label><label>Salida<textarea className="mono-input" value={block.output ?? ''} onChange={(e) => onChange({ ...block, output: e.target.value })} /></label></>}
    {block.type === 'quote' && <><label>Texto<textarea value={block.text} onChange={(e) => onChange({ ...block, text: e.target.value })} /></label><label>Autor<input value={block.author ?? ''} onChange={(e) => onChange({ ...block, author: e.target.value })} /></label></>}
    {block.type === 'callout' && <><label>Título<input value={block.title ?? ''} onChange={(e) => onChange({ ...block, title: e.target.value })} /></label><label>Texto<textarea value={block.text} onChange={(e) => onChange({ ...block, text: e.target.value })} /></label><label>Tono<select value={block.tone ?? 'info'} onChange={(e) => onChange({ ...block, tone: e.target.value as 'info' | 'success' | 'warning' | 'danger' })}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="danger">Danger</option></select></label></>}
    {block.type === 'quadrant' && <QuadrantEditor block={block} onChange={onChange} />}
    {block.type === 'columns' && <>{block.items.map((item, i) => <div className="sub-editor" key={i}><ItemHead title={`Columna ${i + 1}`} disabled={block.items.length <= 1} onRemove={() => onChange({ ...block, items: block.items.filter((_, n) => n !== i), ratio: block.ratio?.filter((_, n) => n !== i) })} /><label>Título<input value={item.title ?? ''} onChange={e => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, title: e.target.value } : x) })} /></label><NestedBlocksEditor label="Bloques de la columna" blocks={item.blocks} onChange={blocks => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, blocks } : x) })} /></div>)}<AddItem label="Columna" onClick={() => onChange({ ...block, items: [...block.items, { title: `Columna ${block.items.length + 1}`, blocks: [] }], ratio: block.ratio ? [...block.ratio, 1] : undefined })} /></>}
    {block.type === 'tabs' && <>{block.tabs.map((tab, i) => <div className="sub-editor" key={i}><ItemHead title={`Tab ${i + 1}`} disabled={block.tabs.length <= 1} onRemove={() => onChange({ ...block, tabs: block.tabs.filter((_, n) => n !== i) })} /><label>Tab<input value={tab.label} onChange={(e) => onChange({ ...block, tabs: block.tabs.map((x, n) => n === i ? { ...x, label: e.target.value } : x) })} /></label><label>Título<input value={tab.title??''} onChange={(e) => onChange({ ...block, tabs: block.tabs.map((x, n) => n === i ? { ...x, title: e.target.value } : x) })} /></label><label>Texto simple / fallback<textarea value={tab.text??''} onChange={(e) => onChange({ ...block, tabs: block.tabs.map((x, n) => n === i ? { ...x, text: e.target.value } : x) })} /></label><NestedBlocksEditor label="Contenido enriquecido" blocks={tab.blocks??[]} onChange={blocks=>onChange({...block,tabs:block.tabs.map((x,n)=>n===i?{...x,blocks}:x)})}/></div>)}<AddItem label="Tab" onClick={() => onChange({ ...block, tabs: [...block.tabs, { label: `Tab ${block.tabs.length + 1}`, text: 'Contenido' }] })} /></>}
    {block.type === 'steps' && <>{block.items.map((step, i) => <div className="sub-editor" key={i}><ItemHead title={`Paso ${i + 1}`} disabled={block.items.length <= 1} onRemove={() => onChange({ ...block, items: block.items.filter((_, n) => n !== i) })} /><label>Paso<input value={step.title} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, title: e.target.value } : x) })} /></label><label>Texto simple / fallback<textarea value={step.text??''} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, text: e.target.value } : x) })} /></label><NestedBlocksEditor label="Contenido enriquecido" blocks={step.blocks??[]} onChange={blocks=>onChange({...block,items:block.items.map((x,n)=>n===i?{...x,blocks}:x)})}/></div>)}<AddItem label="Paso" onClick={() => onChange({ ...block, items: [...block.items, { title: `Paso ${block.items.length + 1}`, text: 'Descripción' }] })} /></>}
    {block.type === 'tooltip' && <><label>Etiqueta<input value={block.label} onChange={(e)=>onChange({...block,label:e.target.value})}/></label><label>Tooltip<textarea value={block.text} onChange={(e)=>onChange({...block,text:e.target.value})}/></label></>}
    {block.type === 'modal' && <><label>Botón<input value={block.buttonLabel} onChange={(e)=>onChange({...block,buttonLabel:e.target.value})}/></label><label>Título<input value={block.title} onChange={(e)=>onChange({...block,title:e.target.value})}/></label><label>Texto simple / fallback<textarea value={block.text??''} onChange={(e)=>onChange({...block,text:e.target.value})}/></label><NestedBlocksEditor label="Contenido enriquecido" blocks={block.blocks??[]} onChange={blocks=>onChange({...block,blocks})}/></>}
    {block.type === 'accordion' && <><label>Título<input value={block.title??''} onChange={e=>onChange({...block,title:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={Boolean(block.allowMultiple)} onChange={e=>onChange({...block,allowMultiple:e.target.checked})}/> Permitir varios abiertos</label>{block.items.map((item,i)=><div className="sub-editor" key={i}><ItemHead title={`Sección ${i+1}`} disabled={block.items.length<=1} onRemove={()=>onChange({...block,items:block.items.filter((_,n)=>n!==i)})}/><label>Encabezado<input value={item.title} onChange={e=>onChange({...block,items:block.items.map((x,n)=>n===i?{...x,title:e.target.value}:x)})}/></label><label>Texto simple / fallback<textarea value={item.text??''} onChange={e=>onChange({...block,items:block.items.map((x,n)=>n===i?{...x,text:e.target.value}:x)})}/></label><NestedBlocksEditor label="Contenido enriquecido" blocks={item.blocks??[]} onChange={blocks=>onChange({...block,items:block.items.map((x,n)=>n===i?{...x,blocks}:x)})}/></div>)}<AddItem label="Sección" onClick={()=>onChange({...block,items:[...block.items,{title:`Sección ${block.items.length+1}`,text:'Contenido'}]})}/></>}
    {block.type === 'drawer' && <><label>Botón<input value={block.buttonLabel} onChange={e=>onChange({...block,buttonLabel:e.target.value})}/></label><label>Título<input value={block.title} onChange={e=>onChange({...block,title:e.target.value})}/></label><div className="block-meta-row"><label>Lado<select value={block.side??'right'} onChange={e=>onChange({...block,side:e.target.value as 'left'|'right'})}><option value="right">Derecha</option><option value="left">Izquierda</option></select></label><label>Ancho<select value={block.width??'md'} onChange={e=>onChange({...block,width:e.target.value as 'sm'|'md'|'lg'})}><option value="sm">Chico</option><option value="md">Mediano</option><option value="lg">Grande</option></select></label></div><label>Texto simple / fallback<textarea value={block.text??''} onChange={e=>onChange({...block,text:e.target.value})}/></label><NestedBlocksEditor label="Contenido enriquecido" blocks={block.blocks??[]} onChange={blocks=>onChange({...block,blocks})}/></>}
    {block.type === 'flipcard' && <><label>Frente<input value={block.frontTitle} onChange={(e)=>onChange({...block,frontTitle:e.target.value})}/></label><label>Texto frente<textarea value={block.frontText ?? ''} onChange={(e)=>onChange({...block,frontText:e.target.value})}/></label><label>Dorso<input value={block.backTitle} onChange={(e)=>onChange({...block,backTitle:e.target.value})}/></label><label>Texto dorso<textarea value={block.backText} onChange={(e)=>onChange({...block,backText:e.target.value})}/></label></>}
    {block.type === 'beforeAfter' && <><label>Antes<textarea value={block.beforeText} onChange={(e)=>onChange({...block,beforeText:e.target.value})}/></label><label>Después<textarea value={block.afterText} onChange={(e)=>onChange({...block,afterText:e.target.value})}/></label></>}
    {block.type === 'timeline' && <>{block.items.map((item, i) => <div className="sub-editor" key={i}><ItemHead title={`Hito ${i + 1}`} disabled={block.items.length <= 1} onRemove={() => onChange({ ...block, items: block.items.filter((_, n) => n !== i) })} /><label>Título<input value={item.title} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, title: e.target.value } : x) })} /></label><label>Texto<textarea value={item.text ?? ''} onChange={(e) => onChange({ ...block, items: block.items.map((x, n) => n === i ? { ...x, text: e.target.value } : x) })} /></label></div>)}<AddItem label="Hito" onClick={() => onChange({ ...block, items: [...block.items, { title: `Paso ${block.items.length + 1}`, text: 'Descripción' }] })} /></>}
    {block.type === 'hotspots' && <><label>Asset<input value={block.src} onChange={(e) => onChange({ ...block, src: e.target.value })} /></label><label>Texto alternativo<input value={block.alt ?? ''} onChange={(e) => onChange({ ...block, alt: e.target.value })} /></label>{block.points.map((point, i) => <div className="sub-editor" key={i}><ItemHead title={`Punto ${i + 1}`} disabled={block.points.length <= 1} onRemove={() => onChange({ ...block, points: block.points.filter((_, n) => n !== i) })} /><div className="block-meta-row"><label>X %<input type="number" min="0" max="100" value={point.x} onChange={(e) => onChange({ ...block, points: block.points.map((x, n) => n === i ? { ...x, x: Number(e.target.value) } : x) })} /></label><label>Y %<input type="number" min="0" max="100" value={point.y} onChange={(e) => onChange({ ...block, points: block.points.map((x, n) => n === i ? { ...x, y: Number(e.target.value) } : x) })} /></label></div><label>Etiqueta<input value={point.label} onChange={(e) => onChange({ ...block, points: block.points.map((x, n) => n === i ? { ...x, label: e.target.value } : x) })} /></label><label>Texto simple / fallback<textarea value={point.text??''} onChange={(e) => onChange({ ...block, points: block.points.map((x, n) => n === i ? { ...x, text: e.target.value } : x) })} /></label><NestedBlocksEditor label="Contenido enriquecido" blocks={point.blocks??[]} onChange={blocks=>onChange({...block,points:block.points.map((x,n)=>n===i?{...x,blocks}:x)})}/></div>)}<AddItem label="Punto" onClick={() => onChange({ ...block, points: [...block.points, { x: 50, y: 50, label: String(block.points.length + 1), text: 'Punto de interés' }] })} /></>}
    {block.type === 'architecture' && <ArchitectureEditor block={block} onChange={onChange} />}
    {block.type === 'chart' && <ChartEditor block={block} onChange={onChange}/>}
    {block.type === 'simulation' && <><label>Título<input value={block.title ?? ''} onChange={(e)=>onChange({...block,title:e.target.value})}/></label><div className="block-meta-row"><label>Mín<input type="number" value={block.min ?? 0} onChange={(e)=>onChange({...block,min:Number(e.target.value)})}/></label><label>Máx<input type="number" value={block.max ?? 100} onChange={(e)=>onChange({...block,max:Number(e.target.value)})}/></label></div><label>Etiqueta métrica<input value={block.metricLabel ?? ''} onChange={(e)=>onChange({...block,metricLabel:e.target.value})}/></label></>}
    {block.type === 'image' && <><label>Asset<input value={block.src} onChange={(e)=>onChange({...block,src:e.target.value})}/></label><label>Texto alternativo<input value={block.alt ?? ''} onChange={(e)=>onChange({...block,alt:e.target.value})}/></label><label>Caption<input value={block.caption ?? ''} onChange={(e)=>onChange({...block,caption:e.target.value})}/></label><label>Ajuste<select value={block.fit ?? 'contain'} onChange={(e)=>onChange({...block,fit:e.target.value as 'contain'|'cover'})}><option value="contain">Contain</option><option value="cover">Cover</option></select></label></>}
    {['timeline','hotspots'].includes(block.type) && <p className="editor-hint">Este componente se renderiza y conserva completo. La edición de sus subpuntos se hace mejor desde el ZIP/JSON en esta v3; el editor visual de canvas cubre posiciones libres.</p>}
    {!embedded && meta}
  </div>;
}


/** Editor de la matriz 2x2 (p.ej. verdadero/falso positivo/negativo). */
function QuadrantEditor({ block, onChange }: { block: Extract<SlideBlock, { type: 'quadrant' }>; onChange: (block: SlideBlock) => void }) {
  const patchCell = (index: number, patch: { title?: string; text?: string; tone?: 'success' | 'danger' | 'neutral' }) => {
    const cells = [...block.cells] as typeof block.cells;
    cells[index] = { ...cells[index], ...patch };
    onChange({ ...block, cells });
  };
  const names = ['Arriba-izquierda', 'Arriba-derecha', 'Abajo-izquierda', 'Abajo-derecha'];
  return <>
    <label>Título<input value={block.title ?? ''} onChange={(e) => onChange({ ...block, title: e.target.value })} /></label>
    <div className="block-meta-row">
      <label>Columna 1<input value={block.colLabels[0]} onChange={(e) => onChange({ ...block, colLabels: [e.target.value, block.colLabels[1]] })} /></label>
      <label>Columna 2<input value={block.colLabels[1]} onChange={(e) => onChange({ ...block, colLabels: [block.colLabels[0], e.target.value] })} /></label>
    </div>
    <div className="block-meta-row">
      <label>Fila 1<input value={block.rowLabels[0]} onChange={(e) => onChange({ ...block, rowLabels: [e.target.value, block.rowLabels[1]] })} /></label>
      <label>Fila 2<input value={block.rowLabels[1]} onChange={(e) => onChange({ ...block, rowLabels: [block.rowLabels[0], e.target.value] })} /></label>
    </div>
    {block.cells.map((cell, i) => <div className="sub-editor" key={i}>
      <ItemHead title={names[i]} disabled onRemove={() => {}} />
      <label>Título<input value={cell.title} onChange={(e) => patchCell(i, { title: e.target.value })} /></label>
      <label>Texto<textarea value={cell.text ?? ''} onChange={(e) => patchCell(i, { text: e.target.value })} /></label>
      <label>Tono<select value={cell.tone ?? 'neutral'} onChange={(e) => patchCell(i, { tone: e.target.value as 'success' | 'danger' | 'neutral' })}><option value="neutral">Neutral</option><option value="success">Success</option><option value="danger">Danger</option></select></label>
    </div>)}
  </>;
}

function ChartEditor({block,onChange}:{block:Extract<SlideBlock,{type:'chart'}>;onChange:(block:SlideBlock)=>void}){
  const count=Math.max(block.labels.length,block.values.length,1); const rows=Array.from({length:count},(_,i)=>({label:block.labels[i]??`Dato ${i+1}`,value:block.values[i]??0}));
  function patchRow(index:number,patch:{label?:string;value?:number}){const next=rows.map((row,i)=>i===index?{...row,...patch}:row);onChange({...block,labels:next.map(x=>x.label),values:next.map(x=>x.value)});}
  function add(){onChange({...block,labels:[...block.labels,`Dato ${count+1}`],values:[...block.values,0]});}
  function remove(index:number){if(count<=1)return;onChange({...block,labels:rows.filter((_,i)=>i!==index).map(x=>x.label),values:rows.filter((_,i)=>i!==index).map(x=>x.value)});}
  return <><label>Título<input value={block.title??''} onChange={e=>onChange({...block,title:e.target.value})}/></label><label>Tipo<select value={block.chart} onChange={e=>onChange({...block,chart:e.target.value as Extract<SlideBlock,{type:'chart'}>['chart']})}><option value="bar">Barras</option><option value="line">Línea</option><option value="area">Área</option><option value="donut">Donut</option><option value="pie">Pie</option><option value="radar">Radar</option><option value="progress">Progress</option><option value="gauge">Gauge</option><option value="funnel">Funnel</option></select></label><div className="chart-data-editor"><div className="chart-data-head"><span>Etiqueta</span><span>Valor</span><span/></div>{rows.map((row,i)=><div className="chart-data-row" key={i}><input value={row.label} onChange={e=>patchRow(i,{label:e.target.value})}/><input type="number" value={row.value} onChange={e=>patchRow(i,{value:Number(e.target.value)})}/><button onClick={()=>remove(i)} title="Eliminar">×</button></div>)}<button className="secondary-button full-width" onClick={add}>+ Serie / dato</button></div><div className="block-meta-row"><label>Sufijo<input value={block.suffix??''} onChange={e=>onChange({...block,suffix:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={block.showValues!==false} onChange={e=>onChange({...block,showValues:e.target.checked})}/> Valores</label></div><div className="block-meta-row"><label>Eje X<input value={block.xLabel??''} onChange={e=>onChange({...block,xLabel:e.target.value})}/></label><label>Eje Y<input value={block.yLabel??''} onChange={e=>onChange({...block,yLabel:e.target.value})}/></label></div><label className="check-row"><input type="checkbox" checked={Boolean(block.showLegend)} onChange={e=>onChange({...block,showLegend:e.target.checked})}/> Mostrar leyenda</label></>;
}

/** Editor de arquitectura: nodos con posición y tipo, más las conexiones entre ellos. */
function ArchitectureEditor({ block, onChange }: { block: Extract<SlideBlock, { type: 'architecture' }>; onChange: (block: SlideBlock) => void }) {
  const { nodes, edges } = block;
  const patchNode = (i: number, patch: Partial<ArchitectureNode>) => onChange({ ...block, nodes: nodes.map((n, x) => x === i ? { ...n, ...patch } : n) });
  const removeNode = (i: number) => { const id = nodes[i].id; onChange({ ...block, nodes: nodes.filter((_, x) => x !== i), edges: edges.filter((e) => e.from !== id && e.to !== id) }); };
  const addNode = () => { const id = `n${nodes.length + 1}-${Math.random().toString(36).slice(2, 6)}`; onChange({ ...block, nodes: [...nodes, { id, label: `Nodo ${nodes.length + 1}`, x: 50, y: 50, kind: 'service' }] }); };
  return <>
    <label>Al hacer clic en un nodo<select value={block.detailView ?? 'drawer'} onChange={e => onChange({ ...block, detailView: e.target.value as typeof block.detailView })}>
      <option value="drawer">Panel lateral</option><option value="modal">Modal centrado</option><option value="inline">Panel debajo del diagrama</option>
    </select></label>
    <p className="editor-hint">El clic abre el detalle y las conexiones del nodo. Probalo en la vista previa.</p>
    <strong className="sub-group-title">Nodos</strong>
    {nodes.map((node, i) => <div className="sub-editor" key={node.id}>
      <ItemHead title={node.label || `Nodo ${i + 1}`} disabled={nodes.length <= 1} onRemove={() => removeNode(i)} />
      <label>Etiqueta<input value={node.label} onChange={(e) => patchNode(i, { label: e.target.value })} /></label>
      <label>Detalle<input value={node.caption ?? ''} onChange={(e) => patchNode(i, { caption: e.target.value })} /></label>
      <label>Texto cuando no hay bloques<textarea value={node.text ?? ''} placeholder="Explicación, contexto o instrucciones…" onChange={e => patchNode(i, { text: e.target.value })} /></label>
      {!node.blocks?.length && node.text && <button type="button" className="secondary-button" onClick={() => patchNode(i, { blocks: [{ type: 'text', text: node.text! }] })}>Usar texto como bloque</button>}
      <NestedBlocksEditor label="Bloques del panel" blocks={node.blocks ?? []} onChange={blocks => patchNode(i, { blocks })} />
      <p className="editor-hint">Agregá uno o varios bloques: se muestran en orden al abrir este nodo. Si hay bloques, reemplazan el texto simple.</p>
      <div className="block-meta-row">
        <label>X %<input type="number" min="0" max="100" value={node.x} onChange={(e) => patchNode(i, { x: Number(e.target.value) })} /></label>
        <label>Y %<input type="number" min="0" max="100" value={node.y} onChange={(e) => patchNode(i, { y: Number(e.target.value) })} /></label>
      </div>
      <label>Tipo<select value={node.kind ?? 'service'} onChange={(e) => patchNode(i, { kind: e.target.value as ArchitectureNode['kind'] })}><option value="client">Cliente</option><option value="service">Servicio</option><option value="data">Datos</option><option value="cloud">Cloud</option></select></label>
    </div>)}
    <AddItem label="Nodo" onClick={addNode} />
    <strong className="sub-group-title">Conexiones</strong>
    {edges.map((edge, i) => <div className="sub-editor" key={i}>
      <ItemHead title={`Conexión ${i + 1}`} onRemove={() => onChange({ ...block, edges: edges.filter((_, x) => x !== i) })} />
      <div className="block-meta-row">
        <label>Desde<select value={edge.from} onChange={(e) => onChange({ ...block, edges: edges.map((x, n) => n === i ? { ...x, from: e.target.value } : x) })}>{nodes.map((n) => <option key={n.id} value={n.id}>{n.label}</option>)}</select></label>
        <label>Hasta<select value={edge.to} onChange={(e) => onChange({ ...block, edges: edges.map((x, n) => n === i ? { ...x, to: e.target.value } : x) })}>{nodes.map((n) => <option key={n.id} value={n.id}>{n.label}</option>)}</select></label>
      </div>
      <label>Etiqueta<input value={edge.label ?? ''} onChange={(e) => onChange({ ...block, edges: edges.map((x, n) => n === i ? { ...x, label: e.target.value } : x) })} /></label>
    </div>)}
    <AddItem label="Conexión" onClick={() => nodes.length >= 2 && onChange({ ...block, edges: [...edges, { from: nodes[0].id, to: nodes[1].id }] })} />
  </>;
}
