import type { IconType } from 'react-icons';
import { HorusecIcon } from './HorusecIcon';
import { SiAngular, SiAnsible, SiApache, SiApacheairflow, SiApachecassandra, SiApachejmeter, SiApachekafka, SiApachemaven, SiApachespark, SiArgo, SiBun, SiC, SiCircleci, SiClickhouse, SiCloudflare, SiCplusplus, SiCypress, SiDart, SiDatadog, SiDebian, SiDeno, SiDigitalocean, SiDjango, SiDocker, SiDotnet, SiElastic, SiElasticsearch, SiElixir, SiEnvoyproxy, SiFastapi, SiFigma, SiFirebase, SiFlask, SiFluentd, SiFlutter, SiGit, SiGithub, SiGithubactions, SiGitlab, SiGnubash, SiGo, SiGooglecloud, SiGradle, SiGrafana, SiHaskell, SiHelm, SiHtml5, SiInfluxdb, SiInsomnia, SiIntellijidea, SiIstio, SiJaeger, SiJavascript, SiJenkins, SiJest, SiJupyter, SiK6, SiKeycloak, SiKibana, SiKotlin, SiKubernetes, SiLaravel, SiLinux, SiLogstash, SiLua, SiMariadb, SiMongodb, SiMysql, SiNeo4J, SiNeovim, SiNetlify, SiNewrelic, SiNextdotjs, SiNginx, SiNodedotjs, SiNpm, SiNuxt, SiOpentelemetry, SiOwasp, SiPhp, SiPnpm, SiPodman, SiPostgresql, SiPostman, SiPrometheus, SiPulumi, SiPython, SiPytorch, SiQuarkus, SiR, SiRabbitmq, SiReact, SiRedhat, SiRedis, SiRuby, SiRust, SiScala, SiSelenium, SiSentry, SiSnowflake, SiSnyk, SiSonarqubeserver, SiSpring, SiSqlite, SiSupabase, SiSvelte, SiSwagger, SiSwift, SiTailwindcss, SiTensorflow, SiTerraform, SiTraefikproxy, SiTrivy, SiTypescript, SiUbuntu, SiVault, SiVercel, SiVite, SiVitest, SiVuedotjs, SiYarn } from 'react-icons/si';
import { DiCss3, DiHeroku, DiJava } from 'react-icons/di';
import { TbBrandCSharp, TbCloud } from 'react-icons/tb';
import { FaAws } from 'react-icons/fa';
import { VscAzure, VscAzureDevops, VscVscode } from 'react-icons/vsc';

export interface TechIcon {
  id: string;
  name: string;
  category: string;
  color: string;
  keywords: string;
  icon: IconType;
}

// Curated SVGs are bundled locally; see THIRD_PARTY_ICONS.md for sources.
export const TECH_ICONS: TechIcon[] = [
  { id: "python", name: "Python", category: "Lenguajes", color: "#3776AB", keywords: "py", icon: SiPython },
  { id: "go", name: "Go", category: "Lenguajes", color: "#00ADD8", keywords: "golang", icon: SiGo },
  { id: "java", name: "Java", category: "Lenguajes", color: "#E76F00", keywords: "jvm", icon: DiJava },
  { id: "c", name: "C", category: "Lenguajes", color: "#A8B9CC", keywords: "ansi", icon: SiC },
  { id: "cplusplus", name: "C++", category: "Lenguajes", color: "#00599C", keywords: "cpp cxx", icon: SiCplusplus },
  { id: "csharp", name: "C#", category: "Lenguajes", color: "#9B4F96", keywords: "csharp dotnet", icon: TbBrandCSharp },
  { id: "javascript", name: "JavaScript", category: "Lenguajes", color: "#F7DF1E", keywords: "js", icon: SiJavascript },
  { id: "typescript", name: "TypeScript", category: "Lenguajes", color: "#3178C6", keywords: "ts", icon: SiTypescript },
  { id: "rust", name: "Rust", category: "Lenguajes", color: "#DEA584", keywords: "rs", icon: SiRust },
  { id: "kotlin", name: "Kotlin", category: "Lenguajes", color: "#7F52FF", keywords: "jvm android", icon: SiKotlin },
  { id: "swift", name: "Swift", category: "Lenguajes", color: "#F05138", keywords: "ios", icon: SiSwift },
  { id: "php", name: "PHP", category: "Lenguajes", color: "#777BB4", keywords: "backend", icon: SiPhp },
  { id: "ruby", name: "Ruby", category: "Lenguajes", color: "#CC342D", keywords: "rb", icon: SiRuby },
  { id: "dart", name: "Dart", category: "Lenguajes", color: "#0175C2", keywords: "flutter", icon: SiDart },
  { id: "scala", name: "Scala", category: "Lenguajes", color: "#DC322F", keywords: "jvm", icon: SiScala },
  { id: "elixir", name: "Elixir", category: "Lenguajes", color: "#8C61A1", keywords: "beam", icon: SiElixir },
  { id: "haskell", name: "Haskell", category: "Lenguajes", color: "#5D4F85", keywords: "functional", icon: SiHaskell },
  { id: "lua", name: "Lua", category: "Lenguajes", color: "#6C75C3", keywords: "scripting", icon: SiLua },
  { id: "r", name: "R", category: "Lenguajes", color: "#276DC3", keywords: "statistics", icon: SiR },
  { id: "bash", name: "Bash", category: "Lenguajes", color: "#4EAA25", keywords: "shell terminal sh", icon: SiGnubash },
  { id: "html", name: "HTML5", category: "Lenguajes", color: "#E34F26", keywords: "web", icon: SiHtml5 },
  { id: "css", name: "CSS", category: "Lenguajes", color: "#1572B6", keywords: "web styles", icon: DiCss3 },
  { id: "aws", name: "AWS", category: "Cloud", color: "#FF9900", keywords: "amazon web services nube", icon: FaAws },
  { id: "azure", name: "Azure", category: "Cloud", color: "#0078D4", keywords: "microsoft cloud nube", icon: VscAzure },
  { id: "googlecloud", name: "Google Cloud", category: "Cloud", color: "#4285F4", keywords: "gcp nube", icon: SiGooglecloud },
  { id: "cloud", name: "Cloud", category: "Cloud", color: "#38BDF8", keywords: "nube genérica", icon: TbCloud },
  { id: "cloudflare", name: "Cloudflare", category: "Cloud", color: "#F38020", keywords: "cdn dns", icon: SiCloudflare },
  { id: "digitalocean", name: "DigitalOcean", category: "Cloud", color: "#0080FF", keywords: "hosting", icon: SiDigitalocean },
  { id: "firebase", name: "Firebase", category: "Cloud", color: "#DD2C00", keywords: "google baas", icon: SiFirebase },
  { id: "vercel", name: "Vercel", category: "Cloud", color: "#A3A3A3", keywords: "hosting deploy", icon: SiVercel },
  { id: "netlify", name: "Netlify", category: "Cloud", color: "#00C7B7", keywords: "hosting", icon: SiNetlify },
  { id: "heroku", name: "Heroku", category: "Cloud", color: "#9D7BDC", keywords: "paas", icon: DiHeroku },
  { id: "supabase", name: "Supabase", category: "Cloud", color: "#3FCF8E", keywords: "baas postgres", icon: SiSupabase },
  { id: "kubernetes", name: "Kubernetes", category: "DevOps", color: "#326CE5", keywords: "k8s orchestration", icon: SiKubernetes },
  { id: "docker", name: "Docker", category: "DevOps", color: "#2496ED", keywords: "containers contenedores", icon: SiDocker },
  { id: "podman", name: "Podman", category: "DevOps", color: "#892CA0", keywords: "containers", icon: SiPodman },
  { id: "helm", name: "Helm", category: "DevOps", color: "#6C83CB", keywords: "k8s charts", icon: SiHelm },
  { id: "argo", name: "Argo CD", category: "DevOps", color: "#EF7B4D", keywords: "argocd gitops", icon: SiArgo },
  { id: "terraform", name: "Terraform", category: "DevOps", color: "#844FBA", keywords: "iac hashicorp", icon: SiTerraform },
  { id: "ansible", name: "Ansible", category: "DevOps", color: "#EE0000", keywords: "automation", icon: SiAnsible },
  { id: "pulumi", name: "Pulumi", category: "DevOps", color: "#8A3391", keywords: "iac", icon: SiPulumi },
  { id: "jenkins", name: "Jenkins", category: "DevOps", color: "#D24939", keywords: "ci cd pipelines", icon: SiJenkins },
  { id: "githubactions", name: "GitHub Actions", category: "DevOps", color: "#2088FF", keywords: "ci cd pipelines", icon: SiGithubactions },
  { id: "gitlab", name: "GitLab", category: "DevOps", color: "#FC6D26", keywords: "ci cd", icon: SiGitlab },
  { id: "azuredevops", name: "Azure DevOps", category: "DevOps", color: "#0078D7", keywords: "microsoft ci cd", icon: VscAzureDevops },
  { id: "circleci", name: "CircleCI", category: "DevOps", color: "#A3A3A3", keywords: "ci cd", icon: SiCircleci },
  { id: "nginx", name: "NGINX", category: "DevOps", color: "#009639", keywords: "proxy webserver", icon: SiNginx },
  { id: "apache", name: "Apache HTTP Server", category: "DevOps", color: "#D22128", keywords: "httpd webserver", icon: SiApache },
  { id: "traefik", name: "Traefik", category: "DevOps", color: "#24A1C1", keywords: "proxy ingress", icon: SiTraefikproxy },
  { id: "istio", name: "Istio", category: "DevOps", color: "#466BB0", keywords: "service mesh", icon: SiIstio },
  { id: "envoy", name: "Envoy", category: "DevOps", color: "#AC6199", keywords: "proxy service mesh", icon: SiEnvoyproxy },
  { id: "linux", name: "Linux", category: "DevOps", color: "#FCC624", keywords: "os tux", icon: SiLinux },
  { id: "ubuntu", name: "Ubuntu", category: "DevOps", color: "#E95420", keywords: "linux", icon: SiUbuntu },
  { id: "debian", name: "Debian", category: "DevOps", color: "#A81D33", keywords: "linux", icon: SiDebian },
  { id: "redhat", name: "Red Hat", category: "DevOps", color: "#EE0000", keywords: "rhel openshift", icon: SiRedhat },
  { id: "grafana", name: "Grafana", category: "Observabilidad", color: "#F46800", keywords: "dashboards monitoring métricas", icon: SiGrafana },
  { id: "prometheus", name: "Prometheus", category: "Observabilidad", color: "#E6522C", keywords: "monitoring métricas", icon: SiPrometheus },
  { id: "k6", name: "k6", category: "Observabilidad", color: "#7D64FF", keywords: "grafana load testing carga", icon: SiK6 },
  { id: "opentelemetry", name: "OpenTelemetry", category: "Observabilidad", color: "#F5A800", keywords: "otel tracing", icon: SiOpentelemetry },
  { id: "jaeger", name: "Jaeger", category: "Observabilidad", color: "#66CFE3", keywords: "traces tracing", icon: SiJaeger },
  { id: "datadog", name: "Datadog", category: "Observabilidad", color: "#9F72D6", keywords: "monitoring apm", icon: SiDatadog },
  { id: "newrelic", name: "New Relic", category: "Observabilidad", color: "#1CE783", keywords: "apm", icon: SiNewrelic },
  { id: "sentry", name: "Sentry", category: "Observabilidad", color: "#C69BB9", keywords: "errors tracking", icon: SiSentry },
  { id: "elastic", name: "Elastic", category: "Observabilidad", color: "#FED10A", keywords: "elk logs", icon: SiElastic },
  { id: "kibana", name: "Kibana", category: "Observabilidad", color: "#F04E98", keywords: "elk logs", icon: SiKibana },
  { id: "logstash", name: "Logstash", category: "Observabilidad", color: "#F2B84B", keywords: "elk logs", icon: SiLogstash },
  { id: "fluentd", name: "Fluentd", category: "Observabilidad", color: "#0E83C8", keywords: "logs", icon: SiFluentd },
  { id: "jmeter", name: "Apache JMeter", category: "Observabilidad", color: "#D22128", keywords: "load testing carga", icon: SiApachejmeter },
  { id: "postgresql", name: "PostgreSQL", category: "Datos", color: "#4169E1", keywords: "postgres sql database", icon: SiPostgresql },
  { id: "mysql", name: "MySQL", category: "Datos", color: "#4479A1", keywords: "sql database", icon: SiMysql },
  { id: "mariadb", name: "MariaDB", category: "Datos", color: "#B0896A", keywords: "sql database", icon: SiMariadb },
  { id: "sqlite", name: "SQLite", category: "Datos", color: "#45A5D0", keywords: "sql embedded", icon: SiSqlite },
  { id: "mongodb", name: "MongoDB", category: "Datos", color: "#47A248", keywords: "nosql", icon: SiMongodb },
  { id: "redis", name: "Redis", category: "Datos", color: "#FF4438", keywords: "cache", icon: SiRedis },
  { id: "elasticsearch", name: "Elasticsearch", category: "Datos", color: "#FED10A", keywords: "search elk", icon: SiElasticsearch },
  { id: "kafka", name: "Apache Kafka", category: "Datos", color: "#B6B6C0", keywords: "events streaming", icon: SiApachekafka },
  { id: "rabbitmq", name: "RabbitMQ", category: "Datos", color: "#FF6600", keywords: "messaging queue", icon: SiRabbitmq },
  { id: "cassandra", name: "Apache Cassandra", category: "Datos", color: "#1287B1", keywords: "nosql", icon: SiApachecassandra },
  { id: "clickhouse", name: "ClickHouse", category: "Datos", color: "#FFCC01", keywords: "analytics", icon: SiClickhouse },
  { id: "influxdb", name: "InfluxDB", category: "Datos", color: "#22ADF6", keywords: "timeseries", icon: SiInfluxdb },
  { id: "neo4j", name: "Neo4j", category: "Datos", color: "#4581C3", keywords: "graph", icon: SiNeo4J },
  { id: "snowflake", name: "Snowflake", category: "Datos", color: "#29B5E8", keywords: "warehouse", icon: SiSnowflake },
  { id: "spark", name: "Apache Spark", category: "Datos", color: "#E25A1C", keywords: "big data", icon: SiApachespark },
  { id: "airflow", name: "Apache Airflow", category: "Datos", color: "#00C7D4", keywords: "etl orchestration", icon: SiApacheairflow },
  { id: "react", name: "React", category: "Frameworks", color: "#61DAFB", keywords: "frontend jsx", icon: SiReact },
  { id: "vue", name: "Vue.js", category: "Frameworks", color: "#4FC08D", keywords: "frontend", icon: SiVuedotjs },
  { id: "angular", name: "Angular", category: "Frameworks", color: "#DD0031", keywords: "frontend", icon: SiAngular },
  { id: "svelte", name: "Svelte", category: "Frameworks", color: "#FF3E00", keywords: "frontend", icon: SiSvelte },
  { id: "nextjs", name: "Next.js", category: "Frameworks", color: "#A3A3A3", keywords: "react ssr", icon: SiNextdotjs },
  { id: "nuxt", name: "Nuxt", category: "Frameworks", color: "#00DC82", keywords: "vue ssr", icon: SiNuxt },
  { id: "nodejs", name: "Node.js", category: "Frameworks", color: "#5FA04E", keywords: "javascript runtime", icon: SiNodedotjs },
  { id: "deno", name: "Deno", category: "Frameworks", color: "#A3A3A3", keywords: "runtime", icon: SiDeno },
  { id: "bun", name: "Bun", category: "Frameworks", color: "#FBF0DF", keywords: "runtime", icon: SiBun },
  { id: "spring", name: "Spring", category: "Frameworks", color: "#6DB33F", keywords: "java boot", icon: SiSpring },
  { id: "quarkus", name: "Quarkus", category: "Frameworks", color: "#4695EB", keywords: "java", icon: SiQuarkus },
  { id: "django", name: "Django", category: "Frameworks", color: "#44B78B", keywords: "python", icon: SiDjango },
  { id: "fastapi", name: "FastAPI", category: "Frameworks", color: "#009688", keywords: "python", icon: SiFastapi },
  { id: "flask", name: "Flask", category: "Frameworks", color: "#A3A3A3", keywords: "python", icon: SiFlask },
  { id: "laravel", name: "Laravel", category: "Frameworks", color: "#FF2D20", keywords: "php", icon: SiLaravel },
  { id: "dotnet", name: ".NET", category: "Frameworks", color: "#916BFF", keywords: "c# microsoft", icon: SiDotnet },
  { id: "flutter", name: "Flutter", category: "Frameworks", color: "#02569B", keywords: "mobile dart", icon: SiFlutter },
  { id: "tailwind", name: "Tailwind CSS", category: "Frameworks", color: "#06B6D4", keywords: "styles css", icon: SiTailwindcss },
  { id: "vite", name: "Vite", category: "Frameworks", color: "#646CFF", keywords: "build bundler", icon: SiVite },
  { id: "horusec", name: "Horusec", category: "Seguridad", color: "#ED733C", keywords: "sast zup devsecops", icon: HorusecIcon },
  { id: "sonarqube", name: "SonarQube", category: "Seguridad", color: "#4E9BCD", keywords: "sast quality gate", icon: SiSonarqubeserver },
  { id: "snyk", name: "Snyk", category: "Seguridad", color: "#AA8CE5", keywords: "security sca", icon: SiSnyk },
  { id: "trivy", name: "Trivy", category: "Seguridad", color: "#69B5FF", keywords: "container vulnerability scanner", icon: SiTrivy },
  { id: "owasp", name: "OWASP", category: "Seguridad", color: "#A3A3A3", keywords: "security top10", icon: SiOwasp },
  { id: "vault", name: "Vault", category: "Seguridad", color: "#FFEC6E", keywords: "hashicorp secrets", icon: SiVault },
  { id: "keycloak", name: "Keycloak", category: "Seguridad", color: "#69B6DD", keywords: "iam auth", icon: SiKeycloak },
  { id: "git", name: "Git", category: "Herramientas", color: "#F05032", keywords: "version control", icon: SiGit },
  { id: "github", name: "GitHub", category: "Herramientas", color: "#A3A3A3", keywords: "repository", icon: SiGithub },
  { id: "vscode", name: "Visual Studio Code", category: "Herramientas", color: "#23A9F2", keywords: "editor ide vs code", icon: VscVscode },
  { id: "intellij", name: "IntelliJ IDEA", category: "Herramientas", color: "#E65C95", keywords: "jetbrains java ide", icon: SiIntellijidea },
  { id: "neovim", name: "Neovim", category: "Herramientas", color: "#57A143", keywords: "editor vim", icon: SiNeovim },
  { id: "postman", name: "Postman", category: "Herramientas", color: "#FF6C37", keywords: "api testing", icon: SiPostman },
  { id: "insomnia", name: "Insomnia", category: "Herramientas", color: "#9575FF", keywords: "api testing", icon: SiInsomnia },
  { id: "swagger", name: "Swagger", category: "Herramientas", color: "#85EA2D", keywords: "openapi", icon: SiSwagger },
  { id: "npm", name: "npm", category: "Herramientas", color: "#CB3837", keywords: "packages", icon: SiNpm },
  { id: "pnpm", name: "pnpm", category: "Herramientas", color: "#F69220", keywords: "packages", icon: SiPnpm },
  { id: "yarn", name: "Yarn", category: "Herramientas", color: "#2C8EBB", keywords: "packages", icon: SiYarn },
  { id: "maven", name: "Apache Maven", category: "Herramientas", color: "#C71A36", keywords: "java build", icon: SiApachemaven },
  { id: "gradle", name: "Gradle", category: "Herramientas", color: "#4DC9C0", keywords: "java build", icon: SiGradle },
  { id: "jest", name: "Jest", category: "Herramientas", color: "#C21325", keywords: "test javascript", icon: SiJest },
  { id: "vitest", name: "Vitest", category: "Herramientas", color: "#6E9F18", keywords: "test javascript", icon: SiVitest },
  { id: "cypress", name: "Cypress", category: "Herramientas", color: "#69D3A7", keywords: "e2e test", icon: SiCypress },
  { id: "selenium", name: "Selenium", category: "Herramientas", color: "#43B02A", keywords: "e2e test", icon: SiSelenium },
  { id: "figma", name: "Figma", category: "Herramientas", color: "#F24E1E", keywords: "design", icon: SiFigma },
  { id: "jupyter", name: "Jupyter", category: "Herramientas", color: "#F37626", keywords: "notebook python", icon: SiJupyter },
  { id: "pytorch", name: "PyTorch", category: "Herramientas", color: "#EE4C2C", keywords: "ai ml", icon: SiPytorch },
  { id: "tensorflow", name: "TensorFlow", category: "Herramientas", color: "#FF6F00", keywords: "ai ml", icon: SiTensorflow },
];

export const TECH_ICON_BY_ID = new Map(TECH_ICONS.map(icon => [icon.id, icon]));
export const TECH_ICON_CATEGORIES = [...new Set(TECH_ICONS.map(icon => icon.category))];
